# Generated by Django 3.2.7 on 2021-10-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('sale_type', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=100)),
                ('phone2', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('year_built', models.CharField(max_length=150)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('room', models.IntegerField()),
                ('lot_size', models.CharField(max_length=100)),
                ('main_pic', models.ImageField(blank=True, upload_to='house/pictures')),
                ('address', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.contract')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.seller')),
            ],
        ),
    ]
