# Generated by Django 3.2.7 on 2021-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pic_2',
            field=models.ImageField(blank=True, upload_to='house/pictures'),
        ),
        migrations.AddField(
            model_name='house',
            name='pic_3',
            field=models.ImageField(blank=True, upload_to='house/pictures'),
        ),
        migrations.AddField(
            model_name='house',
            name='pic_4',
            field=models.ImageField(blank=True, upload_to='house/pictures'),
        ),
        migrations.AddField(
            model_name='house',
            name='pic_5',
            field=models.ImageField(blank=True, upload_to='house/pictures'),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_pic',
            field=models.ImageField(upload_to='house/pictures'),
        ),
    ]
