# Generated by Django 3.2.7 on 2021-10-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20211004_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='sale_type',
            new_name='seller_type',
        ),
    ]
