# Generated by Django 3.2.7 on 2021-10-04 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_rename_sale_type_seller_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='garage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
